CREATE TABLE sys.LOCATIONS (
    LOCATION_ID      SMALLINT NOT NULL,
    ADDRESS          VARCHAR(40),
    POSTAL_CODE      VARCHAR(12),
    CITY             VARCHAR(30),
    COUNTRY          VARCHAR(30),
    CONSTRAINT LOC_PK PRIMARY KEY(LOCATION_ID)
)

CREATE TABLE sys.JOBS (
    JOB_ID       VARCHAR(10) NOT NULL,
    JOB_TITLE    VARCHAR(35),
    CONSTRAINT JOBS_PK PRIMARY KEY(JOB_ID)
)

CREATE TABLE sys.SKILLS (
    SKILL_ID       VARCHAR(10) NOT NULL,
    SKILL_TITLE    VARCHAR(35),
    CONSTRAINT SKILLS_PK PRIMARY KEY(SKILL_ID)
)

CREATE TABLE sys.EMPLOYEES (
    EMPLOYEE_ID      SMALLINT NOT NULL,
    FIRST_NAME       VARCHAR(20),
    LAST_NAME        VARCHAR(25),
    EMAIL            VARCHAR(25),
    PHONE_NUMBER     VARCHAR(20),
    CONSTRAINT EMPL_PK PRIMARY KEY(EMPLOYEE_ID)
)

CREATE TABLE sys.SKILL_HISTORY (
    SH_HASH_KEY     SMALLINT NOT NULL,
    EMPLOYEE_ID     SMALLINT NOT NULL,
    SKILL_DATE      TIMESTAMP,
    SKILL_ID        VARCHAR(10),
    SKILL_LEVEL     VARCHAR(30),
    CONSTRAINT SH_PK PRIMARY KEY(SH_HASH_KEY),
    CONSTRAINT SH_EMPL_FK FOREIGN KEY(EMPLOYEE_ID)
    REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT SH_SKILLS_FK FOREIGN KEY(SKILL_ID)
    REFERENCES SKILLS(SKILL_ID)
)

CREATE TABLE sys.DEPARTMENTS (
    DEPARTMENT_ID     SMALLINT NOT NULL,
    DEPARTMENT_TITLE  VARCHAR(30),
    MANAGER_ID        SMALLINT,
    LOCATION_ID       SMALLINT,
    CONSTRAINT DEP_PK PRIMARY KEY(DEPARTMENT_ID),
    CONSTRAINT DEP_EMPL_FK FOREIGN KEY(MANAGER_ID)
    REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT DEP_LOC_FK FOREIGN KEY(LOCATION_ID)
    REFERENCES LOCATIONS(LOCATION_ID)
)

CREATE TABLE sys.JOB_HISTORY (
    JH_HASH_KEY     SMALLINT NOT NULL,
    EMPLOYEE_ID     SMALLINT NOT NULL,
    START_DATE      TIMESTAMP,
    END_DATE        TIMESTAMP,
    JOB_ID          VARCHAR(10),
    DEPARTMENT_ID   SMALLINT,
    CONSTRAINT JH_PK PRIMARY KEY(JH_HASH_KEY),
    CONSTRAINT JH_EMPL_FK FOREIGN KEY(EMPLOYEE_ID)
    REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT JH_JOBS_FK FOREIGN KEY(JOB_ID)
    REFERENCES JOBS(JOB_ID),
    CONSTRAINT JH_DEP_FK FOREIGN KEY(DEPARTMENT_ID)
    REFERENCES DEPARTMENTS(DEPARTMENT_ID)
)

